name: Test Robot Framework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4  # Atualizado para v4

    - name: Set up Python
      uses: actions/setup-python@v5  # Atualizado para v5
      with:
        python-version: '3.8'

    - name: Display Python version
      run: python --version

    - name: Display pip version
      run: pip --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework

    - name: List installed packages
      run: pip list

    - name: Run Robot Framework tests
      run: |
        robot path/to/your/tests

    - name: Upload Robot Framework reports
      uses: actions/upload-artifact@v4  # Atualizado para v4
      with:
        name: robot-reports
        path: path/to/your/reports