name:  Testes com RObot Framework API

on:  
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Robot Framework
      uses: joonvena/robotframework-docker-action@v1.0
      with:
        robot reports dir: 'reports'
        
    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: ${{ !cancelled() }}
      with:
        name: robot-reports
        path: reports
        retention-days: 2