name: Test Robot Framework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4  # Atualizado para v4

    - name: Set up Python
      uses: actions/setup-python@v4  # Certifique-se de usar a versão mais recente
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework

    - name: Run Robot Framework tests
      run: |
        robot path/to/your/tests

    - name: Upload Robot Framework reports
      uses: actions/upload-artifact@v4  # Atualizado para v4
      with:
        name: robot-reports
        path: path/to/your/reports